
spring:
  application:
    name: Order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.102.135.76/sell?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: 106.13.81.170
    port: 5672
    username: admin
    password: admin
